Repository Makepad-fr/fbjs, pull requests merged in 2021-02, with the labels that each got.

#18 multilanguage support for login
  src/index.js
Labels: enhancement, good first issue

#14 Facebook login issue fix
  src/index.js
  src/selectors/facebook.js
Labels: bug

#21 Console flooding removed
  src/index.js
Labels: documentation

#24 Readme updated
  .all-contributorsrc
  README.md
  package.json
Labels: documentation, enhancement
